In [1]:
import pandas as pd
import torch
import numpy as np
import random
from random import shuffle
from matplotlib import pyplot as plt
import seaborn as sns
from torch.utils.data import TensorDataset, DataLoader
import wget
import os
import aiohttp
import asyncio
np.random.seed(17)
random.seed(17)
torch.manual_seed(17)
from fpl import FPL
from player import Player
from team import Team
from data_processor import get_fpl, get_players, get_teams, get_training_datasets
from models import PreviousScoreModel, AvgScoreModel

In [2]:
fpl = await get_fpl()
team_feature_names = ["npxGA"]
teams = get_teams(team_feature_names=team_feature_names, visualize=False)
player_feature_names = ["total_points"]
players = await get_players(player_feature_names, visualize=False, num_players=10)

In [3]:
train_loader, test_loader = get_training_datasets(players, teams)
train_loader, test_loader

(<torch.utils.data.dataloader.DataLoader at 0x7ff4a12e5a10>,
 <torch.utils.data.dataloader.DataLoader at 0x7ff4ec3509d0>)

In [4]:
previous_score_model = PreviousScoreModel()
avg_score_model = AvgScoreModel()
print(avg_score_model.eval(test_loader))
print(previous_score_model.eval(test_loader))

0.1930128205128205
tensor([0.0625, 0.1250, 0.5000, 0.0000, 0.0000], dtype=torch.float64) tensor([0.3846, 0.5385, 0.1538, 0.0000, 0.0000], dtype=torch.float64)
tensor([ 0.1250, -0.1875,  0.0000,  1.0000,  0.0000], dtype=torch.float64) tensor([0.1538, 0.6923, 0.0000, 0.5385, 0.0769], dtype=torch.float64)
tensor([0.0000, 0.1250, 0.3125, 0.0000, 0.0000], dtype=torch.float64) tensor([0.0769, 0.0769, 0.1538, 0.0000, 0.0000], dtype=torch.float64)
0.18749999999999997
